//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMurtazinIS121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdIzmereniya
    {
        public EdIzmereniya()
        {
            this.Ingredients = new HashSet<Ingredients>();
        }
    
        public string EdinIzmereniya { get; set; }
    
        public virtual ICollection<Ingredients> Ingredients { get; set; }
    }
}
