//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMurtazinIS121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransactions
    {
        public int TransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Quantity { get; set; }
        public string TransactionType { get; set; }
        public int EmployeeID { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> IngredientID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Ingredients Ingredients { get; set; }
        public virtual TransactionType TransactionType1 { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
